#Dissecando uma informação
x = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(x))
print('É um número? ', x.isnumeric())
print('É alfabético?', x.isalpha())
print('É alfanumérico? ', x.isalnum())
print('Só tem espaços? ', x.isspace())
print('Está em maiúsculas? ', x.isupper())
print('Está em minúsculas? ', x.islower())
print('Está capitalizada? ', x.istitle())
